sdkversion: "4.1.0"
name: "compliancetest_ruby"
version: "1.0"
vendor: "rhomobile"
build: "release"
applog: "rholog.txt"
iphone:
  configuration: "Release"
  sdk: "iphonesimulator7.1"
  provisionprofile: 
  codesignidentity: "iPhone Developer"
  entitlements: ./production/Entitlements.plist
  BundleIdentifier: "com.rhomobile.compliancerubytest"
  BundleURLScheme: "compliancerubytest"
wp8:
  productid: "da37e740-9d27-0131-ad03-0023241f0ea9"
android:
  manifest_template: "AndroidManifest.erb"
  ajax_api_bridge: false
  version: "4.2.2"
  capabilities:
  extensions:
    - barcode
    - indicators
    - mediaplayer
    - audiocapture
    - printing
    - printing_zebra
    - signature
    - screenorientation
wm:
  ajax_api_bridge: false
#sdk: "MC3000c50b (ARMV4I)"
  sdk: "Windows Mobile 6.5.3 Professional DTK (ARMV4I)"
  extensions:
    - barcode
    - indicators
    - mediaplayer
    - audiocapture
    - printing
    - printing_zebra
    - signature
    - screenorientation
extensions:
  - rhoconnect-client
app_type: "rhoelements"
capabilities:

#rhohub:
#  url: "https://appstaging.rhohub.com/api/v1/"
#connection:
#  proxy: "http://wwwgate0.mot.com:1080"
